# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Jacob Senecal
email: senecaljacob@gmail.com
description: > # this means to ignore newlines until "url:"
  Personal website for Jacob Senecal, developer, scientist, engineer. 
footer_text: >

url:  # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: # your GitHub user name
bitbucket_username: jsene
twitter_username: # your Twitter handle
linkedin_username: jacob-senecal-481552111
scholar_userid: # your Google Scholar ID
orcid_id: # your ORCID ID
contact_note: >
  Email is the easiest way to reach me.

google_analytics: UA-111993378-1 # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Recent Work
blog_description: featured personal & professional projects

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons:  true
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Senecal

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
